"""
SPARQL client for EvdoGraph's GraphDB endpoint.

This file has exactly two public surfaces:

  1. validate_sparql() — checks whether a SPARQL string is syntactically
     correct.

  2. SparqlClient.execute() — sends a validated SPARQL query to GraphDB
     over HTTP and returns the results.

The separation matters because validate_sparql() is called inside a retry
loop (up to 3 times per request). Making a network call on every validation
attempt would be slow and fragile. Only a confirmed-valid query ever touches the network.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, cast

# SPARQLWrapper is a third-party library that handles the HTTP details of
# talking to a SPARQL endpoint: URL-encoding the query, setting the correct
# Accept header, and parsing the JSON response.
# `JSON` is a constant that tells SPARQLWrapper to request results in
# application/sparql-results+json format (the standard for SELECT queries).
from SPARQLWrapper import JSON, SPARQLWrapper

logger = logging.getLogger(__name__)


@dataclass
class SparqlResult:
    """The structured result of a SPARQL SELECT query.

    This is what execute() returns, and what the pipeline forwards to the
    frontend as a ResultsEvent (rendered as a table in the UI).

    Fields
    ------
    columns : list[str]
        The variable names from the SELECT clause.
        These become the table column headers in the frontend.
    rows : list[dict[str, Any]]
        One dict per result row. Each dict maps a column name to its value.

        IMPORTANT — unbound variables become None:
        If a query uses OPTIONAL { ... } and a value is missing for a given
        row, that column's value will be None (JSON null) rather than the
        key being absent. The key is always present for every column.

    """

    columns: list[str]
    rows: list[dict[str, Any]]


def validate_sparql(query: str) -> str | None:
    """Check whether a SPARQL string is syntactically correct.

    Uses rdflib's built-in SPARQL parser to check the query grammar entirely
    in memory. This is called after every LLM generation attempt (up to 3
    times per request) to decide whether to execute or retry.

    WHAT IT CHECKS
    --------------
    Syntax only: correct keyword order, valid triple patterns, proper use of
    PREFIX, FILTER, OPTIONAL, UNION, variable names, etc.

    WHAT IT DOES NOT CHECK
    ----------------------
    - Whether the URIs / properties / classes actually exist in GraphDB.
    - Whether the query will return any results.
    - Whether the query will time out on a large dataset.

    A query can pass this check and still return zero rows, or even trigger
    a GraphDB-level error (e.g. referencing a property that does not exist
    in the ontology). The retry loop is only triggered by parse failures —
    it cannot help with semantically wrong queries.

    Parameters
    ----------
    query : str
        The raw SPARQL string generated by the LLM.

    Returns
    -------
    str | None
        None if the query is valid (no error).
        A human-readable error message string if parsing failed. This string
        is injected into the retry prompt so the LLM knows what went wrong.
    """
    from rdflib.plugins.sparql.parser import parseQuery

    try:
        parseQuery(query)
        return None  # valid — no error
    except Exception as exc:
        # rdflib can raise several different exception types depending on
        # what part of the grammar fails. Catching broadly and converting to
        # a string gives the retry prompt a readable explanation without
        # needing to handle each exception type separately.
        return str(exc)


class SparqlClient:
    """HTTP client for sending SELECT queries to the GraphDB SPARQL endpoint.

    Constructed once per request in `_make_pipeline()` inside `app/api/query.py`:
        SparqlClient(settings.graphdb_endpoint)

    Only SELECT queries are supported. CONSTRUCT and ASK queries return
    different response formats that execute() does not handle.
    """

    def __init__(self, endpoint: str) -> None:
        self._endpoint = endpoint

    def execute(self, query: str) -> SparqlResult:
        """Send a SPARQL SELECT query to GraphDB and return structured results.

        This is the only method that makes a real network call. It is called
        once per request, in Phase 3 of the pipeline, after the query has
        already been validated by validate_sparql().

        HOW THE HTTP CALL WORKS
        -----------------------
        SPARQLWrapper encodes the query into a URL parameter and sends an
        HTTP GET to `{endpoint}?query={url-encoded-sparql}`. GraphDB responds
        with a JSON object in the W3C SPARQL 1.1 Query Results format:

            {
              "head": { "vars": ["title", "author"] },
              "results": {
                "bindings": [
                  {"title": {"value": "Αλγόριθμοι"}, "author": {"value": "Knuth"}},
                  {"title": {"value": "Γραφήματα"}}   ← "author" not bound here
                ]
              }
            }

        execute() unwraps this structure into a flat SparqlResult.

        WHAT CAN GO WRONG
        -----------------
        - Network error (GraphDB unreachable, timeout): SPARQLWrapper raises
          an exception. execute() catches it, logs it, and re-raises it as a
          RuntimeError. The pipeline's route handler maps this to HTTP 502.
        - GraphDB rejects the query (e.g. the query is syntactically valid
          but uses a feature GraphDB does not support): same — RuntimeError.
        - Query is valid but GraphDB returns no rows: NOT an error. execute()
          returns a SparqlResult with an empty `rows` list.

        Parameters
        ----------
        query : str
            A syntactically valid SPARQL SELECT query string.

        Returns
        -------
        SparqlResult
            Columns and rows extracted from GraphDB's JSON response.
            Unbound OPTIONAL variables appear as None in the row dicts.

        Raises
        ------
        RuntimeError
            If the HTTP call fails or GraphDB returns an error response.
            The original exception is chained (`from exc`) so the full
            traceback is preserved for debugging.
        """
        # A new SPARQLWrapper is created for each call — no persistent
        # connection is reused. Fine for single-user thesis-demo workload.
        wrapper = SPARQLWrapper(self._endpoint)
        wrapper.setQuery(query)
        wrapper.setReturnFormat(JSON)  # request application/sparql-results+json
        
        logger.info("GraphDB query -> %s:\n%s", self._endpoint, query)

        try:
            # wrapper.query() sends the HTTP request.
            # .convert() reads the response body and parses the JSON into a dict.
            # Cast is defensive only: SPARQLWrapper returns Any, but we know it's
            # a dict because we requested JSON via wrapper.setReturnFormat(JSON).
            # Does not affect runtime behavior.
            raw = cast(dict, wrapper.query().convert())
        except Exception as exc:
            logger.error("SPARQL execution failed: %s", exc)
            # Re-raise as RuntimeError so callers don't need to know about
            # SPARQLWrapper internals. `from exc` preserves the original
            # traceback so it still shows up in logs.
            # NOTE: the embedded {exc} detail is intentionally preserved here
            # for operator logs.
            raise RuntimeError(f"SPARQL execution failed: {exc}") from exc

        # Extract column names from "head".vars — defensive .get() in case
        # the response is missing the key (malformed but non-crashing response).
        columns: list[str] = raw.get("head", {}).get("vars", [])

        # Each binding is one result row as a dict of {var: {"value": "..."}}.
        bindings: list[dict] = raw.get("results", {}).get("bindings", [])

        # Unwrap the {"value": "..."} envelope for each cell.
        # `col in b` is False for unbound OPTIONAL variables → those become None.
        rows = [
            {col: b[col]["value"] if col in b else None for col in columns}
            for b in bindings
        ]

        logger.info(
            "GraphDB result: %d columns %s, %d rows. First 3: %s",
            len(columns), columns, len(rows), rows[:3],
        )

        return SparqlResult(columns=columns, rows=rows)
