"""TF-IDF char-n-gram ranked retrieval for course/book titles.

WHAT THIS MODULE DOES
---------------------
Given a phrase extracted from a user question (e.g. "αρχιτεκτονικη υπολογιστων"),
``rank_titles`` ranks the real KG course title corpus against that phrase and
returns the closest matching title(s) with cosine similarity scores.

The caller (``hints.build_grounding_hints``) uses these matches to inject an
exact ``VALUES ?title { "..." }`` binding into the LLM system prompt, replacing
the imprecise single-stem ``CONTAINS`` filter that would otherwise apply.

WHY CHAR N-GRAMS?
-----------------
Greek titles in EvdoGraph are stored in ALL-CAPS accent-free form after
``normalize_greek`` (e.g. "αρχιτεκτονικη υπολογιστων").  User queries arrive
with accents and inflected forms.  Character n-grams over normalized strings
sidestep both problems:

  - **Case/accent:** ``normalize_greek`` strips both before vectorization, so
    "Αρχιτεκτονική" and "ΑΡΧΙΤΕΚΤΟΝΙΚΗ" both become "αρχιτεκτονικη".
  - **Inflection:** "υπολογιστων" (gen pl) shares char trigrams and 4-grams
    with the stem "υπολογιστ" — the inflectional suffix contributes fewer,
    lower-weight features, so the normalized title still ranks highest.
  - **Word order:** TF-IDF weights terms independently, so "υπολογιστων
    αρχιτεκτονικη" scores the same as "αρχιτεκτονικη υπολογιστων".

Analyzer ``"char_wb"`` pads each word with word-boundary sentinels (spaces)
before extracting n-grams, preserving word boundaries as features.  This gives
better precision than plain ``"char"`` for Greek inflection at word endings.

RANKER SEAM
-----------
``rank_titles`` delegates to ``_rank``, which takes an ``_IndexState``.
Swapping the ranking backend (e.g. to BM25 via ``rank_bm25.BM25Okapi``) means
only ``_build_index`` and ``_rank`` need changing; the public ``TitleMatch``
signature and callers remain stable.  See ADR-015.

CORPUS SOURCE
-------------
The title corpus is loaded from ``get_course_surface_map()`` in
``app.grounding.gazetteer``, which reads ``scripts/grounding_labels.json``.
That file must have been generated by ``scripts/dump_labels.py`` with the
``"courses"`` key present.  If absent, ``rank_titles`` returns ``[]`` (no-op).

MODULE-LEVEL CACHE
------------------
``_get_index()`` fits the vectorizer once and caches the result in
``_INDEX_CACHE``.  Fitting is cheap for ~10k titles but not free; caching
avoids re-fitting on every query request.

For testing, use ``rank_titles_from_corpus(surface_map, phrase, k)`` which
takes an explicit corpus dict and bypasses the module cache entirely.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from app.grounding.gazetteer import get_course_surface_map
from app.grounding.normalize import normalize_greek


# ---------------------------------------------------------------------------
# Public data types
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class TitleMatch:
    """A single ranked result from ``rank_titles``.

    Attributes
    ----------
    normalized_title : str
        The accent-free, lowercase key used for ranking (output of
        ``normalize_greek`` applied to the raw title).
    score : float
        Cosine similarity between the query vector and this title's vector,
        in the range [0, 1].  Higher is better.
    surface_forms : list[str]
        All raw KG title strings that normalize to ``normalized_title``.
        Includes both ALL-CAPS accent-free variants ("ΑΡΧΙΤΕΚΤΟΝΙΚΗ
        ΥΠΟΛΟΓΙΣΤΩΝ") and mixed-case accented variants ("Αρχιτεκτονική
        Υπολογιστών"), whichever are present in the KG.  The caller should
        emit all of them in a SPARQL ``VALUES`` binding so the query matches
        regardless of how the title is stored.
    """

    normalized_title: str
    score: float
    surface_forms: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Internal index state
# ---------------------------------------------------------------------------


@dataclass
class _IndexState:
    """All fitted artifacts needed to score a query against the corpus.

    ``vectorizer`` is None and ``matrix`` is None when the corpus is empty
    (e.g. ``grounding_labels.json`` predates the "courses" key).  ``_rank``
    short-circuits on None and returns an empty list.
    """

    vectorizer: TfidfVectorizer | None
    """Fitted TfidfVectorizer (None for empty corpus)."""

    matrix: object  # scipy.sparse.csr_matrix | None
    """Fitted TF-IDF matrix, shape (n_titles, n_features) (None for empty corpus)."""

    normalized_titles: list[str]
    """Ordered list of normalized title strings — row i of ``matrix``."""

    surface_map: dict[str, list[str]]
    """Mapping normalize_greek(title) → [raw surface form, ...].  Used to
    look up raw forms for the matched normalized key."""


# Module-level cache: populated on first call to _get_index().
_INDEX_CACHE: _IndexState | None = None


# ---------------------------------------------------------------------------
# Index construction
# ---------------------------------------------------------------------------


def _build_index(surface_map: dict[str, list[str]]) -> _IndexState:
    """Fit a TF-IDF vectorizer over normalized title strings from ``surface_map``.

    Pure function — no I/O, no module state.  Used both by ``_get_index()``
    (live corpus) and ``rank_titles_from_corpus`` (test corpus).

    Args:
        surface_map: Mapping ``normalize_greek(title)`` → ``[raw title, ...]``.
                     Keys are the documents; values are kept for result lookup.

    Returns:
        An ``_IndexState`` with a fitted vectorizer and matrix, or an empty
        state (both None) if ``surface_map`` is empty.
    """
    normalized_titles = sorted(surface_map.keys())
    if not normalized_titles:
        return _IndexState(
            vectorizer=None,
            matrix=None,
            normalized_titles=[],
            surface_map=surface_map,
        )

    vectorizer = TfidfVectorizer(analyzer="char_wb", ngram_range=(3, 5))
    matrix = vectorizer.fit_transform(normalized_titles)

    return _IndexState(
        vectorizer=vectorizer,
        matrix=matrix,
        normalized_titles=normalized_titles,
        surface_map=surface_map,
    )


def _get_index() -> _IndexState:
    """Return the module-level cached index, building it on first call.

    Reads the live course corpus from ``get_course_surface_map()`` (which
    reads ``scripts/grounding_labels.json``).  Subsequent calls return the
    same cached ``_IndexState`` object.
    """
    global _INDEX_CACHE
    if _INDEX_CACHE is None:
        _INDEX_CACHE = _build_index(get_course_surface_map())
    return _INDEX_CACHE


# ---------------------------------------------------------------------------
# Ranking
# ---------------------------------------------------------------------------


def _rank(phrase: str, k: int, state: _IndexState) -> list[TitleMatch]:
    """Rank corpus titles against ``phrase`` using cosine similarity.

    Pure function — takes an explicit ``_IndexState`` so it can be used by
    both the live ``rank_titles`` and the test helper
    ``rank_titles_from_corpus``.

    Args:
        phrase: Raw user phrase to rank against the corpus.  Will be
                normalized before vectorization.
        k: Maximum number of results to return.
        state: Pre-built index state (vectorizer + matrix + title list).

    Returns:
        List of up to ``k`` ``TitleMatch`` objects sorted by score descending.
        Titles with score 0.0 are excluded (no shared n-gram features at all).
    """
    if state.vectorizer is None or not state.normalized_titles:
        return []

    q_normalized = normalize_greek(phrase)
    if not q_normalized:
        return []

    # Vectorize the query using the already-fitted vocabulary.
    q_vec = state.vectorizer.transform([q_normalized])

    # Compute cosine similarity against every corpus title.
    # cosine_similarity returns shape (1, n_titles); squeeze to 1-D.
    scores: np.ndarray = cosine_similarity(q_vec, state.matrix)[0]  # type: ignore[assignment]

    # Pick top-k indices sorted by score descending.
    top_k = min(k, len(state.normalized_titles))
    top_indices: np.ndarray = np.argsort(scores)[::-1][:top_k]

    results: list[TitleMatch] = []
    for idx in top_indices:
        score = float(scores[idx])
        if score <= 0.0:
            break  # remaining indices have zero overlap — stop early
        norm_title = state.normalized_titles[int(idx)]
        surface_forms = state.surface_map.get(norm_title, [norm_title])
        results.append(TitleMatch(
            normalized_title=norm_title,
            score=score,
            surface_forms=list(surface_forms),
        ))

    return results


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def rank_titles(phrase: str, k: int = 3) -> list[TitleMatch]:
    """Rank the KG course title corpus against ``phrase``.

    Uses the module-level cached TF-IDF index built from the live course
    corpus (``scripts/grounding_labels.json`` → ``get_course_surface_map()``).

    Returns up to ``k`` results sorted by cosine similarity (highest first).
    Returns ``[]`` if the corpus is empty (refresh with
    ``scripts/dump_labels.py``) or if no title shares any char n-gram with
    the phrase.

    The caller (``hints.build_grounding_hints``) is responsible for applying
    the acceptance threshold (``settings.course_match_threshold``) and
    deciding how to format the results in the hint block.

    Args:
        phrase: Raw content phrase from the user question (after entity and
                stopword tokens have been removed).  E.g.
                "αρχιτεκτονικη υπολογιστων".  Accents and casing are
                normalized internally.
        k: Maximum number of ranked candidates to return.  Default 3.

    Returns:
        List of ``TitleMatch`` objects sorted by score descending, length 0..k.
    """
    return _rank(phrase, k, _get_index())


def rank_titles_from_corpus(
    surface_map: dict[str, list[str]],
    phrase: str,
    k: int = 3,
) -> list[TitleMatch]:
    """Rank titles from an explicit corpus dict (for unit tests).

    Identical to ``rank_titles`` but builds a fresh index from ``surface_map``
    instead of reading the live gazetteer.  Does NOT populate or read the
    module-level cache, so tests are isolated from each other and from the
    live data on disk.

    Args:
        surface_map: A ``normalize_greek(title)`` → ``[raw surface form, ...]``
                     dict.  Typically a small fixture corpus.
        phrase: Raw user phrase to rank.
        k: Maximum number of results.

    Returns:
        List of ``TitleMatch`` objects sorted by score descending.
    """
    return _rank(phrase, k, _build_index(surface_map))
